name = "TFG: Command and Conquer"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "688f5ff1e4058cba367d3fc87490bc07ed93f9473dfa485fd137738ceedce6c6"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
